### PR TITLE
Test on Python 3.13

### PR DESCRIPTION
**Pull request by alexrudd2**

### CODE REVIEW

**Comment by alexrudd2** [comment]
The problem is apparently pytest-profiling, which hasn't bothered to release since 2019... but they are apparently resurrecting.

**Review by janiversen — APPROVED** [review]
LGTM, thanks.

**Comment by janiversen** [comment]
Have not seen you for quite a while, nice to see your PR´s again. 

If you feel in mypy/ruff mode, then both framer and serial, should be totally typed. Next up for me is pdu and then transaction.

You missed to change the README, to tell others that we now test on python 3.13 (Thanks for doing that!!).

**Comment by janiversen** [comment]
Your PR is always welcome !

**Pull request merged**
