### PR TITLE
Readme file renamed

### PR DESCRIPTION
**Pull request by theyashjani**
renamed the readme.rst => README.rst

### CODE REVIEW

**Review by janiversen — COMMENTED** [review]
you need to update the reference to readme.rst as well, without that documents cannot be generated

test locally:
```
cd doc
./build_html
```

**Review by janiversen — CHANGES_REQUESTED** [review]
Please ensure document generation works.

**Review by janiversen — APPROVED** [review]
hmmm sphinx accept lower case filenames, so it actually works.

**Comment by janiversen** [comment]
Thanks, it will be available automatically on readthedocs in a couple of minutes (only dev !!!!)

**Comment by theyashjani** [comment]
> you need to update the reference to readme.rst as well, without that documents cannot be generated
> 
> test locally:
> 
> ```
> cd doc
> ./build_html
> ```

understood

**Comment by theyashjani** [comment]
> Thanks, it will be available automatically on readthedocs in a couple of minutes (only dev !!!!)

sure sir

**Pull request merged**
