### PR TITLE
Fix PRs from forks

### PR DESCRIPTION
**Pull request by alexrudd2**
See https://github.com/pymodbus-dev/pymodbus/pull/1515#issuecomment-1520906103

### CODE REVIEW

**Review by jamesbraza — APPROVED** [review]
LGTM

**Comment by alexrudd2** [comment]
Yup, that was it.  Since we normally open PRs from the main repo, it wasn't noticed.

**Comment by alexrudd2** [comment]
Screenshot 2023-04-24 at 5 35 46 PM

OK, now that's just funny.  Since I _opened_ the PR, my approval won't count, and since you don't have the commit bit yours doesn't either.  You'd have to copy my branch to your fork and submit it to me (or just wait for Jan to wake up tomorrow.)

**Comment by jamesbraza** [comment]
I can just wait, no big deal

**Review by janiversen — APPROVED** [review]
ups copy/paste. thanks for catching.

**Pull request merged**
