### PR TITLE
fix getFrameStart for ExceptionResponse

### PR DESCRIPTION
**Pull request by Fredo70**

### CODE REVIEW

**Review by janiversen — APPROVED** [review]
Good catch, this might also be present in the other frame handler. Do you mind checking?

**Comment by janiversen** [comment]
If you run with our venv (see README.RST) then most things are caught in precommit.

For mypy etc run ./check_ci.sh

**Comment by Fredo70** [comment]
> this might also be present in the other frame handler. Do you mind checking?

I'm not sure. I didn't see this construct in the other Framers.

**Comment by Fredo70** [comment]
> If you run with our venv (see README.RST) then most things are caught in precommit.

Unfortunately, I develop under Windows. I already have an old Linux laptop somewhere. But it's too slow.
I have to write down that I have to keep these things in mind. I like to be forgetful ;-)

**Comment by janiversen** [comment]
Python is the same on windows command line, The only script we have is check_ci.sh and that is just a few python commands.

**Pull request merged**
