### PR TITLE
solve more mypy issues with datastore

### PR DESCRIPTION
**Pull request by alexrudd2**
This solves another 15 (counting with `--check-untyped-defs`)

### CODE REVIEW

**Comment by janiversen** [comment]
Now I see where you saw the problems....can you try to remove the ignore, and see if you get a problem with python 3.11 - 3.12...thanks in advance.

**Comment by janiversen** [comment]
I just checked your CI run, it looks a lot as if your dev is not updated (I changed CI a couple of days ago).

**Review by janiversen — APPROVED** [review]
The changes are OK. I like the idea of a TextCell.

**Comment by janiversen** [comment]
Just to be sure, I have cleaned out all cache, and CI are running on dev as I write this....if CI turns green, I think the problem is somewhere else...agree ?

**Comment by janiversen** [comment]
dev is green after a new CI run, so I think the problem with "ignore" is an not updated dev branch ?

**Comment by alexrudd2** [comment]
I think there was a cache problem.  Some of the CI runners failed to even have Python installed

**Pull request merged**
