### PR TITLE
Bug: Fixed caused by passing wrong arg

### PR DESCRIPTION
**Pull request by AKJ7**
* Fixed a bug: `got multiple values for keyword argument 'slave'`

### CODE REVIEW

**Comment by AKJ7** [comment]
Reproduce error:

- Run REPL interface
- use readwrite_register command

**Review by janiversen — COMMENTED** [review]
LGTM.

**Comment by janiversen** [comment]
Ups, I did not check the repl client, good catch. Lets see what CI says.

**Comment by janiversen** [comment]
Thanks, it will be part of the upcoming 3.2 (due in 1-2 weeks).

**Pull request merged**
