### PR TITLE
Forward retry_on_empty and retries to serial

### PR DESCRIPTION
**Pull request by cgernert**
Fixes https://github.com/pymodbus-dev/pymodbus/issues/1331

### CODE REVIEW

**Comment by janiversen** [comment]
You change from reading the external parameters to instead use the stored params, but the stored parameters are not ready, those are assigned in the base class.

**Comment by cgernert** [comment]
> You change from reading the external parameters to instead use the stored params, but the stored parameters are not ready, those are assigned in the base class.

Yeah, I debugged it and don't get the Python code. 
The constructor in base.py seems to remove the parameters from kwargs list, but I don't know why:

      def __init__(
        self,
        framer: str = None,
        timeout: str | float = Defaults.Timeout,
        retries: str | int = Defaults.Retries,
        retry_on_empty: bool = Defaults.RetryOnEmpty,
        close_comm_on_error: bool = Defaults.CloseCommOnError,
        strict: bool = Defaults.Strict,
        broadcast_enable: bool = Defaults.BroadcastEnable,
        reconnect_delay: int = Defaults.ReconnectDelay,
        reconnect_delay_max: int = Defaults.ReconnectDelayMax,
        **kwargs: any,
      )...

**Comment by janiversen** [comment]
????
it removes it, because it uses it.
´´´
        self.params.retry_on_empty = bool(retry_on_empty)
´´´
all parameters used are normally declared, while the rest are kwargs.

**Comment by janiversen** [comment]
Anyhow you must have debugged it very lightly, since:
```
>       self.retry_on_empty = client.params.retry_on_empty
[6042](https://github.com/pymodbus-dev/pymodbus/actions/runs/4314030700/jobs/7527285279#step:6:6043)
E       AttributeError: 'NoneType' object has no attribute 'params'
```
this is a pretty clear signal, that your change was not correct.

**Comment by cgernert** [comment]
> ???? it removes it, because it uses it. ´´´ self.params.retry_on_empty = bool(retry_on_empty) ´´´ all parameters used are normally declared, while the rest are kwargs.

Ah, OK. I don't write Python often. Anyway, that's the source of the problem. I will create another pull request.

**Pull request closed without merging**
