### PR TITLE
CI caching

### PR DESCRIPTION
**Pull request by janiversen**
Let the python build do the caching.

### CODE REVIEW

**Comment by alexrudd2** [comment]
aaaah, no don't do that!  (too late 😆 )

`setup-python` only caches Python (which is fast), and not `pip` (which is slow).  See https://github.com/actions/setup-python/issues/330

Before:
Screenshot 2023-10-16 at 5 01 42 PM

After:
Screenshot 2023-10-16 at 5 01 14 PM

**Comment by janiversen** [comment]
According to the doc it does cache pip, see the parameters used.

**Comment by alexrudd2** [comment]
> According to the doc it does cache pip, see the parameters used.

Yes, that's what the docs say :)  But if you look more closely it only caches the downloads, not the install.  So it's quite slow.  (see screenshots)

**Comment by janiversen** [comment]
I am aware that python-checkout caches the cache, but it a step I needed to make, before making a cache mechanism tailored to us.

**Pull request merged**
