### PR TITLE
Defaulted pylint

### PR DESCRIPTION
**Pull request by jamesbraza**
Before working on https://github.com/pymodbus-dev/pymodbus/issues/1500, I noticed the `pylint` config was way too verbose (repeated many defaults).  This makes it:
- More arduous to update to newer `pylint` and get updated defaults/args
- Hard to determine what non-default behaviors the config is actually calling out

This PR:
- Removed defaulted options
- Removed some over-constraining options that prevented `pylint` from discerning useless suppressions

To see `pylint` defaults: https://github.com/pylint-dev/pylint/blob/v2.15.10/examples/pylintrc

### CODE REVIEW

**Comment by jamesbraza** [comment]
Cc @alexrudd2 @janiversen for review.  not sure why Lock Threads action fails

**Review by alexrudd2 — APPROVED** [review]
LGTM; I'm in favor of deleting stuff!

that said, I don't use pylint myself so I'll defer to @janiversen

**Comment by alexrudd2** [comment]
> not sure why Lock Threads action fails

I'm fairly sure it's because you're opening this from a fork, which won't have the read/write permissions to this repo.

The [Action in question](https://github.com/pymodbus-dev/pymodbus/pull/1508/files) locks old issues (which I personally disagree with but it's Jan's call).  I don't see any reason to run it on pull requests, so it should be possible to remove that trigger.  That will fix this PR from your fork.
```yaml
  pull_request:
    branches:
      - dev
  schedule:
    # Every night at 02:20 UTC.
    - cron: '20 2 * * *'
```

**Comment by jamesbraza** [comment]
I just tested what it's like to bump `pylint` to the current release, and it's pretty easy after this PR.  Just sharing another benefit

**Comment by alexrudd2** [comment]
> I just tested what it's like to bump `pylint` to the current release, and it's pretty easy after this PR. Just sharing another benefit

On my repos I've enabled renovatebot, but I haven't suggested that here yet. o_0

**Review by janiversen — APPROVED** [review]
LGTM.

**Comment by janiversen** [comment]
@alexrudd2 just for the record, I actually agree with you too, but for some reason in this repo most issues are reported on a closed issue and users do not open a new issue. That way we “loose” history (e.g. issues vs version).


The lock forces users to open a new issue (the issue remains open for 10 days, to allow comments relating to the close).

**Comment by janiversen** [comment]
Thanks, looking forward to see more PR, like the bot you talked about (haven’t checked what it does).

**Pull request merged**
