### PR TITLE
More direct readme links for REPL

### PR DESCRIPTION
**Pull request by alexrudd2**
Skip an intermediate page and go directly to the relevant README

### CODE REVIEW

**Review by janiversen — APPROVED** [review]
OK for me, even though I do not understand the difference. When I open the readme in my browser it uses “tree” not “blob”.

**Comment by alexrudd2** [comment]
hmm, `tree` versus `blob` was unexpected, but doesn't matter.

The link for "Pymodbus REPL client" should go directly to `[...]dev/pymodbus/repl/client/README.md` instead of `[...]dev/pymodbus/repl/`

**Comment by janiversen** [comment]
Thanks.

**Comment by janiversen** [comment]
You are now among the 5 most active developers https://github.com/pymodbus-dev/pymodbus/graphs/contributors thanks for your contributions, it helps a lot !

**Pull request merged**
