### PR TITLE
Refactor REPL client to reduce complexity

### PR DESCRIPTION
**Pull request by alexrudd2**
This splits up a large function (complexity 21) into smaller ones within a class.  The tradeoff is more LOC.  What do you think?

### CODE REVIEW

**Comment by dhoomakethu** [comment]
This looks good to me on a first pass, I will spend some more time to see if everything is fine.

My original idea was not to bloat the core  libraries with all these helpers/scripts but add them as separate projects which consumes pymodbus. It will be easier to maintain in that way.

**Review by janiversen — APPROVED** [review]
LGTM, but I will wait for @dhoomakethu 

@dhoomakethu I get your point, but in that case we should move the whole REPL out as a separate repo, and I am not sure that it is worth it.

**Comment by janiversen** [comment]
If @dhoomakethu have concerns later then we will address them.

**Comment by dhoomakethu** [comment]
@janiversen yes, I had plans to move repl as an add-on package for pymodbus. I am not sure if it's worth the effort though.

**Comment by janiversen** [comment]
I think it is not worth the effort, it does in no way disturb the library.

**Pull request merged**
