### PR TITLE
Modbus simulator - Added support for additional datatypes

### PR DESCRIPTION
**Pull request by pnl-jseb**
This update adds native support for some of the most commonly found datatypes in OT systems. This includes support for bitfields, unsigned integers, signed integers, and floating point numbers in multiple word sizes (16 bit, 32 bit and 64 bit).

Relevant changes include:
A reworked version of simulator.py  that relies on struct.unpack, struct.pack, and other native functions to simplifly datatype handling while also incorportating additional checks to ensure the register layout behaves as expected.
In order to simplifly future work development, the Bits field has been renamed bitfield16, while also adding support for 32 and 64 bit fields. To help facilitate adoption, several changes have been done to the project files to ensure a smooth transition. This includes:
	- Updated documentation to reflect new datatypes, including examples.
	- Updated unit tests, to ensure the code works as expected.
	- Updated the simulator example to illustrate how the new datatypes can be used

Resolves [discussion]: #1458
Partially addresses: #1284

### CODE REVIEW

**Comment by janiversen** [comment]
Is this a copy of #2201 ?

**Comment by pnl-jseb** [comment]
Thanks for the feedback, I will do a rollback of the bitfieldXX structures and just keep the bits. As for breaking into smaller chunks, I'm unsure of the best course of action, but I can certainly try to work with you to ensure a smooth merge.

**Comment by janiversen** [comment]
Any progress on this PR ?

**Comment by janiversen** [comment]
Closing due to lack of work (can be reopened if work starts again).

**Pull request closed without merging**
