### PR TITLE
Fix incorrect callback for transport_connect

### LINKED ISSUE #1574: Possibly incorrect invocation of transport_connect in reconnect_timer
```
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py:73: 
RuntimeWarning: coroutine 'BaseTransport.transport_connect' was never awaited
```
I think this was most recently introduced in [2df9599](https://github.com/pymodbus-dev/pymodbus/pull/1541/files#diff-232ea64eea656684ba1d20bc100847b5fabad3d4627d4b8a51c49041ad84897dR374), but there's similar code earlier.
https://github.com/pymodbus-dev/pymodbus/blob/a68582168a863ca1d63cc0c7ecc3713d654cc9cd/pymodbus/transport/transport.py#L369-L372

This code calls `transport_connect` immediately, when I believe the intention is to pass it as an argument to `ensure_future` instead.  In other words, it should have no parentheses.

### PR DESCRIPTION
**Pull request by alexrudd2**
Closes #1574

I would like to catch this in a test, but don't quite know how to write 
the test.

### CODE REVIEW

**Comment by janiversen** [comment]
I know how (now). I will make it later today and make a new release as well.

**Review by janiversen — APPROVED** [review]
Thanks.

**Comment by janiversen** [comment]
Seems something is not right with your change, let me check

**Comment by alexrudd2** [comment]
Nope, this is incorrect.

**Pull request closed without merging**
