### PR TITLE
Try out renovatebot

### PR DESCRIPTION
**Pull request by alexrudd2**

### CODE REVIEW

**Comment by alexrudd2** [comment]
@janiversen If you agree, you'll need to install the bot here: https://github.com/marketplace/renovate

**Comment by alexrudd2** [comment]
you can see it in action on my fork: https://github.com/alexrudd2/pymodbus/pulls

(The amount and type of PRs can be configured)

**Comment by janiversen** [comment]
As far as I can see, this bot is not relevant, with all configurations in pyproject.toml.

**Comment by alexrudd2** [comment]
The bot reads `pyproject.toml` and submits PRs to update dependencies.

https://github.com/alexrudd2/pymodbus/pulls
Screenshot 2023-10-27 at 9 36 02 AM

It also constantly updates an overview of them: https://github.com/alexrudd2/pymodbus/issues/17

**Comment by janiversen** [comment]
the GitHub variant does the same without being depending on an external site.

**Comment by alexrudd2** [comment]
> the GitHub variant does the same without being depending on an external site.

I've used both, and prefer Renovatebot since it's much more powerful and configurable.  That said, I'm OK with using dependabot too.

**Comment by janiversen** [comment]
My preference is clearly dependabot, but we do not really need any of them, we have no reason to always use the newest version of the dependencies.

**Pull request closed without merging**
