### PR TITLE
Change unit to slave (2).

### PR DESCRIPTION
**Pull request by janiversen**

### CODE REVIEW

**Comment by jamesbraza** [comment]
@janiversen I would recommend checking out [`flake8-pytest-style`](https://github.com/m-burst/flake8-pytest-style), you can hook it right into `pre-commit`.

It really helps one best adopt `pytest`'s DSL

**Comment by janiversen** [comment]
I am not sure what the relevance is for this PR ?

**Comment by janiversen** [comment]
But pull requests are welcome.

**Comment by jamesbraza** [comment]
Oh just cuz this PR was about migrating to `pytest`.  Figured I would chip in a tool I found helpful!

image

**Comment by janiversen** [comment]
It might be something for our CI, everything that improves the code is welcome. I think it is overkill to add it to pre-commit, we need to ensure precommit stays very fast.

If you want it integrated, please make a PR:

**Comment by janiversen** [comment]
If you have it installed, then try to run it on the test directory and if it spots anything, please make a PR.

**Comment by alexrudd2** [comment]
> @janiversen I would recommend checking out [`flake8-pytest-style`](https://github.com/m-burst/flake8-pytest-style), you can hook it right into `pre-commit`.
> 
> It really helps one best adopt `pytest`'s DSL

@jamesbraza 
If you are still interested, it's fast and easy to enable in ruff.
https://beta.ruff.rs/docs/rules/#flake8-pytest-style-pt

Personally on my other projects it only found `PT001` and `PT018`.  I found those to be useless and kept it disabled.

```
examples/client_calls.py:213:5: PT018 [*] Assertion should be broken down into multiple parts
examples/client_calls.py:218:5: PT018 [*] Assertion should be broken down into multiple parts
test/test_client.py:41:5: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_client.py:209:5: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_client.py:364:2: PT023 [*] Use `@pytest.mark.skip()` over `@pytest.mark.skip`
test/test_client.py:543:5: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_client_multidrop.py:18:5: PT005 Fixture `_framer` returns a value, remove leading underscore
test/test_client_multidrop.py:23:5: PT005 Fixture `_callback` returns a value, remove leading underscore
test/test_example_client_server.py:77:26: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_example_client_server.py:105:26: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_exceptions.py:30:17: PT017 Found assertion on exception `exc` in `except` block, use `pytest.raises()` instead
test/test_factory.py:99:5: PT004 Fixture `setup` does not return anything, add leading underscore
test/test_framers.py:19:2: PT001 [*] Use `@pytest.fixture()` over `@pytest.fixture`
test/test_framers.py:25:2: PT001 [*] Use `@pytest.fixture()` over `@pytest.fixture`
test/test_logging.py:31:9: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_server_asyncio.py:108:5: PT004 Fixture `setup_teardown` does not return anything, add leading underscore
test/test_server_task.py:152:9: PT015 Assertion always fails, replace with `pytest.fail()`
test/test_server_task.py:152:9: PT017 Found assertion on exception `exc` in `except` block, use `pytest.raises()` instead
test/test_server_task.py:250:13: PT015 Assertion always fails, replace with `pytest.fail()`
test/test_server_task.py:273:9: PT015 Assertion always fails, replace with `pytest.fail()`
test/test_server_task.py:273:9: PT017 Found assertion on exception `exc` in `except` block, use `pytest.raises()` instead
test/test_server_task.py:348:13: PT015 Assertion always fails, replace with `pytest.fail()`
test/test_simulator.py:407:9: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_unix_socket.py:48:28: PT019 Fixture `_mock_run_server` without value is injected as parameter, use `@pytest.mark.usefixtures` instead
test/test_unix_socket.py:55:46: PT019 Fixture `_mock_run_server` without value is injected as parameter, use `@pytest.mark.usefixtures` instead
Found 25 errors.
```

**Comment by janiversen** [comment]
This PR was merged long ago, let's not continue discussing here.

I would not like to run pytest with every commit that is far too slow.

**Comment by janiversen** [comment]
Feel free to make a PR with the above mentioned PTxxx.

**Pull request merged**
